/* ─── State ─── */
var THEME_KEY = 'torbox_theme';
var API_KEY   = 'torbox_api_key';
var currentTheme = 'dark';
function $(id) { return document.getElementById(id); }
var liveDot = $('live-dot'), mainContent = $('main-content'), connectPanel = $('connect-panel');
var apiInput = $('api-key'), saveKeyBtn = $('save-key'), keyStatus = $('key-status');
var pageDomain = $('page-domain'), sendPageBtn = $('send-page'), actionStatus = $('action-status');
var historyEl = $('history-section'), clearHistBtn = $('clear-history'), dashboardBtn = $('open-dashboard');
var toastEl = $('toast'), settingsToggle = $('settings-toggle'), settingsDrawer = $('settings-drawer');
var settingsClose = $('settings-close'), drawerEmail = $('drawer-email');
var drawerThemeLabel = $('drawer-theme-label'), drawerThemeToggle = $('drawer-theme-toggle');
var drawerChangeKey = $('drawer-change-key');
function icon(n,s){var sz=s||14;return '<svg width="'+sz+'" height="'+sz+'" viewBox="0 0 24 24" class="i"><use href="#i-'+n+'"/></svg>';}
var FILE_ICONS = {archive:'archive',video:'video',audio:'audio',image:'image',doc:'doc',app:'app'};
async function get(k){var r=await browser.storage.local.get(k);return r[k];}
async function set(k,v){var o={};o[k]=v;await browser.storage.local.set(o);}
var toastTimer;
function showToast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){toastEl.classList.remove('show');},1500);}
function applyTheme(t){currentTheme=t||'dark';document.body.setAttribute('data-theme',currentTheme);var b=document.querySelector('.accent-bar');if(b)b.style.background=currentTheme==='light'?'linear-gradient(90deg,#04bf8a,#039f75)':'linear-gradient(90deg,#04bf8a,#026873,#04bf8a)';drawerThemeLabel.textContent=currentTheme==='dark'?'Dark':'Light';}
async function toggleTheme(){var n=currentTheme==='dark'?'light':'dark';applyTheme(n);await set(THEME_KEY,n);}
async function initTheme(){applyTheme(await get(THEME_KEY)||'dark');}
async function initApiKey(){var key=await get(API_KEY);if(!key){connectPanel.classList.remove('hidden');return;}var status=await browser.runtime.sendMessage({type:'get-apikey-status'});if(status&&status.valid){showConnected(status.email||'Connected');}else{var result=await browser.runtime.sendMessage({type:'validate-apikey',apiKey:key});if(result.valid){showConnected(result.email||'Connected');}else{apiInput.value=key;connectPanel.classList.remove('hidden');setStatus(keyStatus,'Session expired - reconnect?','error');}}}
function showConnected(email){connectPanel.classList.add('hidden');mainContent.classList.remove('hidden');liveDot.classList.add('live-dot--active');showActions();loadHistory();drawerEmail.textContent=email;}
async function saveApiKey(){var key=apiInput.value.trim();if(!key){setStatus(keyStatus,'Enter your API key.','error');return;}setStatus(keyStatus,'Connecting...');var result=await browser.runtime.sendMessage({type:'validate-apikey',apiKey:key});if(result.valid){await set(API_KEY,key);setStatus(keyStatus,'','');showConnected(result.email||'Connected');showToast('Connected');}else{setStatus(keyStatus,result.error||'Invalid key','error');}}
function showActions(){browser.tabs.query({active:true,currentWindow:true}).then(function(t){if(t[0]&&t[0].url){try{pageDomain.textContent=new URL(t[0].url).hostname;}catch(e){pageDomain.textContent=t[0].url;}}});}
async function sendCurrentPageMagnets(){var key=await get(API_KEY);if(!key){setStatus(actionStatus,'No API key set.','error');return;}setStatus(actionStatus,'Searching page for magnets...');var tabs=await browser.tabs.query({active:true,currentWindow:true});if(!tabs[0])return;try{var results=await browser.tabs.executeScript(tabs[0].id,{code:'Array.from(document.querySelectorAll(\'a[href^="magnet:"]\')).map(function(a){return a.href;})'});var magnets=[...new Set(results[0]||[])];if(magnets.length===0){setStatus(actionStatus,'No magnet links found on this page.','error');return;}setStatus(actionStatus,'Sending '+magnets.length+' magnet(s)...');for(var i=0;i<magnets.length;i++){var fd=new FormData();fd.append('magnet',magnets[i]);fd.append('allow_zip','true');await fetch('https://api.torbox.app/v1/api/torrents/createtorrent',{method:'POST',headers:{'Authorization':'Bearer '+key},body:fd});}setStatus(actionStatus,magnets.length+' magnet(s) sent','success');loadHistory();}catch(err){setStatus(actionStatus,'Error: '+err.message,'error');}}
async function loadHistory(){var result=await browser.runtime.sendMessage({type:'get-history'});var history=result.history||[];if(history.length===0){historyEl.innerHTML='<div class="empty-state">Right-click a magnet or .torrent link &rarr; <strong>Send to TorBox</strong></div>';return;}var html='';for(var i=0;i<history.length;i++){var entry=history[i];var time=new Date(entry.timestamp).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});var typeIcon=FILE_ICONS[entry.fileType]||'file';var typeName=entry.fileType||'file';var badge=entry.cached?'<span class="badge badge--cached">'+icon(typeIcon,10)+' '+typeName+'</span>':'<span class="badge badge--queued">'+icon('clock',10)+' Queued</span>';var name=(entry.name&&entry.name!=='Unknown')?entry.name:(entry.hash?entry.hash.slice(0,16)+'...':'Magnet');var dlBtn=(entry.cached&&entry.torrentId)?'<button class="icon-btn icon-btn--sm" data-action="dl" title="Download">'+icon('download')+'</button>':'<button class="icon-btn icon-btn--sm" data-action="dash" title="Open Dashboard">'+icon('grid')+'</button>';html+='<div class="history-item" data-hash="'+eAttr(entry.hash||'')+'" data-tid="'+(entry.torrentId||'')+'" data-name="'+eAttr(name)+'" data-magnet="'+eAttr(entry.magnet||'')+'"><div class="hi-content"><div class="hi-name" title="'+eAttr(name)+'">'+eHtml(name)+'</div><div class="hi-meta"><span class="hi-time">'+time+'</span>'+badge+'</div></div><div class="hi-actions">'+dlBtn+'<button class="icon-btn icon-btn--sm" data-action="copy" title="Copy magnet">'+icon('copy')+'</button><button class="icon-btn icon-btn--sm" data-action="del" title="Remove">'+icon('close')+'</button></div></div>';}historyEl.innerHTML=html;}
function eHtml(s){if(!s)return '';return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function eAttr(s){if(!s)return '';return s.replace(/&/g,'&amp;').replace(/"/g,'&quot;');}
historyEl.addEventListener('click',async function(e){var btn=e.target.closest('[data-action]');if(!btn)return;var item=btn.closest('.history-item');if(!item)return;var hash=item.dataset.hash;var tid=item.dataset.tid;var magnet=item.dataset.magnet;var name=item.dataset.name||'Unknown';var action=btn.dataset.action;if(action==='dl'&&tid){await browser.runtime.sendMessage({type:'re-download',torrentId:Number(tid),name:name});showToast('Downloading...');}else if(action==='dash'){browser.runtime.sendMessage({type:'open-dashboard'});}else if(action==='copy'){try{await navigator.clipboard.writeText(magnet);showToast('Copied');}catch(e){showToast('Copy failed');}}else if(action==='del'&&hash){await browser.runtime.sendMessage({type:'delete-history-entry',hash:hash});await loadHistory();}});
clearHistBtn.addEventListener('click',async function(){await browser.runtime.sendMessage({type:'clear-history'});await loadHistory();});
dashboardBtn.addEventListener('click',function(){browser.runtime.sendMessage({type:'open-dashboard'});});
settingsToggle.addEventListener('click',function(){settingsDrawer.classList.remove('hidden');});
settingsClose.addEventListener('click',function(){settingsDrawer.classList.add('hidden');});
var drawerScrim=settingsDrawer.querySelector('.drawer-scrim');if(drawerScrim)drawerScrim.addEventListener('click',function(){settingsDrawer.classList.add('hidden');});
drawerThemeToggle.addEventListener('click',toggleTheme);
drawerChangeKey.addEventListener('click',function(){settingsDrawer.classList.add('hidden');connectPanel.classList.remove('hidden');mainContent.classList.add('hidden');liveDot.classList.remove('live-dot--active');apiInput.value='';apiInput.focus();setStatus(keyStatus,'','');});
saveKeyBtn.addEventListener('click',saveApiKey);sendPageBtn.addEventListener('click',sendCurrentPageMagnets);
apiInput.addEventListener('keydown',function(e){if(e.key==='Enter')saveApiKey();});
function setStatus(el,text,type){el.innerHTML=text;el.className='status'+(type?' '+type:'');}
(async function(){await initTheme();await initApiKey();})();
